disabled_rules: # rule identifiers to exclude from running
  - todo
  - type_body_length

opt_in_rules: # some rules are only opt-in
  - control_statement
  - trailing_newline
  - colon
  - comma

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - UnitTests
  - Products
  - Pods
  - Frameworks
  - test/AppDelegate.swift
  - test/SceneDelegate.swift

function_body_length:
  warning: 200
  error: 300

line_length:
  warning: 130
  error: 160

file_length:
  warning: 1000
  error: 1200

cyclomatic_complexity:
  warning: 15
  error: 20

# nested types. Apple allows nested type in their code base, so we allow some nesting levels.
nesting:
  type_level: 5

identifier_name:
  min_length: # only min_length
    warning: 2 # better to be >= 3
  max_length:
    warning: 40
  allowed_symbols: ["_"]
  excluded:
    - rx  # rxswift
    - db  # grdb
    - id  # identifier
    - ms  # milliseconds
    - sr  # study_record
    - fm  # fm value
    - i   # iterator
    - x
    - y
